
services:
  dev-db:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - freecodecamp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:  # caching
    image: redis:alpine
    container_name: redis
    #command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - freecodecamp
    volumes:
      - redis-data:/data
    restart: always

  redisinsight: # RedisInsight web UI
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${REDISINSIGHT_PORT}:5540"
    networks:
      - freecodecamp
    restart: always

  pgadmin: # pgadmin web UI
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - freecodecamp
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dev-db
networks:
  freecodecamp:

volumes:
  postgres_data:
  pgadmin_data:
  redis-data:
